### ISSUE TITLE
Invalid scheme proxy 

### ISSUE THREAD

**Issue by 1923812371283127398123712893126793** [totoroterror/warp-cloner#13]
![Screenshot_20230606-180704_Termux](https://github.com/totoroterror/warp-cloner/assets/104192289/9721ac9f-fdca-4f81-8b77-16511396f9b1)
Yep i ran it on termux the proxies are made by me and works gracefully its the code i think

**Comment by totoroterror** [comment]
Proxy format is `protocol://user:pass@ip:port`
if you specifying only ip:port or in other format - it will probably throw this error.
I haven't tested it, you can send your proxy file there (replacing ip with example.org, for example), and we'll see

**Comment by totoroterror** [comment]
> > Proxy format is `protocol://user:pass@ip:port`, see https://github.com/totoroterror/warp-cloner#proxy-format if you specifying only ip:port or in other format - it will probably throw this error. I haven't tested it, you can send your proxy file there (replacing ip with example.org, for example), and we'll see
> 
> Sure, heres the Proxy file i used [http_proxies (2).txt](https://github.com/totoroterror/warp-cloner/files/11665336/http_proxies.2.txt)

you need to use format `http://206.189.59.223:8080` for example, not a just ip:port
