### ISSUE TITLE
Android problem

### ISSUE THREAD

**Issue by 023948799e213e21b53eb83785356208** [totoroterror/warp-cloner#22]
aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_android -Ideps/build-config/include -Ideps/c-ares/include -I/data/data/com.termux/files/usr/include/python3.11 -c deps/c-ares/src/lib/ares_getnameinfo.c -o build/temp.linux-aarch64-cpython-311/deps/c-ares/src/lib/ares_getnameinfo.o
      deps/c-ares/src/lib/ares_getnameinfo.c:300:15: error: call to undeclared function 'getservbyport_r'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                if (getservbyport_r(port, proto, &se, (void *)tmpbuf,
                    ^
      deps/c-ares/src/lib/ares_getnameinfo.c:300:15: note: did you mean 'getservbyport'?
      /data/data/com.termux/files/usr/include/netdb.h:262:17: note: 'getservbyport' declared here
      struct servent* getservbyport(int __port_in_network_order, const char* __proto);
                      ^
      1 error generated.
      error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycares
  Building wheel for yarl (pyproject.toml) ... done
  Created wheel for yarl: filename=yarl-1.8.2-cp311-cp311-linux_aarch64.whl size=151345 sha256=0754ec4db656cc27ea313367a0c6d137d56ef80eb634b35ca0d2e99a9341b709
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/94/cd/3e/4b106d0785f75161a57556e0b5daffd2ad0e80a6db033e6087
Successfully built aiohttp cffi frozenlist multidict yarl
Failed to build pycares
ERROR: Could not build wheels for pycares, which is required to install pyproject.toml-based projects

**Comment by 023948799e213e21b53eb83785356208** [comment]
Its an issue from pycares

**Comment by totoroterror** [comment]
doesn't related to warp-cloner directly
