### ISSUE TITLE
Continuous "Too many connected devices" error

### ISSUE THREAD

**Issue by Zabooby** [totoroterror/warp-cloner#31]
All the key being generated are printing this error. All options have not been altered. Windows 11

![image](https://github.com/totoroterror/warp-cloner/assets/78969986/87b918d5-deb3-463c-85ac-19ecec12c769)

**Comment by sodareverse** [comment]
Hey, have you fixed this problem?

**Comment by 0x8008** [comment]
> Hey, have you fixed this problem?

Replace the default keys in `src/config.py` with your own ones. The app seems to completely ignore the .env file.

**Comment by Zabooby** [comment]
> Replace the default keys in `src/config.py` with your own ones. The app seems to completely ignore the .env file.

This works but any keys it genereates only have 0.93GB remaining:
![image](https://github.com/totoroterror/warp-cloner/assets/78969986/f64cbe43-03f7-4ec3-823d-a56ee1aa4641)

I've tried a bunch of different keys but still get less than 1GB with all of them:
![image](https://github.com/totoroterror/warp-cloner/assets/78969986/6db05243-4317-4bcc-8466-e4df00b904ba)

**Comment by 0x8008** [comment]
> > Replace the default keys in `src/config.py` with your own ones. The app seems to completely ignore the .env file.
> 
> This works but any keys it generates only have 0.93GB remaining

As the name of this repository implies it CLONES keys instead of creating new ones. If you put a key with 0.93GB in, you'll get a 0.93GB key out. See here, the 7GB ones are ones which have been cloned off a 7GB key I added for testing purposes.
![image](https://github.com/totoroterror/warp-cloner/assets/108335683/48e0ce17-90a7-4813-b89d-a70a3af9abb6)

**Comment by Zabooby** [comment]
> As the name of this repository implies it CLONES keys instead of creating new ones. If you put a key with 0.93GB in, you'll get a 0.93GB key out. See here, the 7GB ones are ones which have been cloned off a 7GB key I added for testing purposes.

Do you know any places where I can get 12-24 PB keys other than the telegram bot? I can't figure out how to register.

**Comment by 0x8008** [comment]
> > As the name of this repository implies it CLONES keys instead of creating new ones. If you put a key with 0.93GB in, you'll get a 0.93GB key out. See here, the 7GB ones are ones which have been cloned off a 7GB key I added for testing purposes.
> 
> Do you know any places where I can get 12-24 PB keys other than the telegram bot? I can't figure out how to register.

Drop me your telegram I'll pass you 5 pieces

**Comment by Zabooby** [comment]
Thanks for the generosity, but that's the issue I have rn. I'm trying to register to telegram with my number but it won't send a verification code, from a few quick searches my number might have been used previously to make an account so I'm stuck. 

Could you send them through discord? My username is zabooby.

**Comment by Jack999** [comment]
> > > Replace the default keys in `src/config.py` with your own ones. The app seems to completely ignore the .env file.
> > 
> > 
> > This works but any keys it generates only have 0.93GB remaining
> 
> As the name of this repository implies it CLONES keys instead of creating new ones. If you put a key with 0.93GB in, you'll get a 0.93GB key out. See here, the 7GB ones are ones which have been cloned off a 7GB key I added for testing purposes. ![image](https://private-user-images.githubusercontent.com/108335683/326286862-48e0ce17-90a7-4813-b89d-a70a3af9abb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MDg2NTcsIm5iZiI6MTcxNTUwODM1NywicGF0aCI6Ii8xMDgzMzU2ODMvMzI2Mjg2ODYyLTQ4ZTBjZTE3LTkwYTctNDgxMy1iODlkLWE3MGEzYWY5YWJiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxMDA1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZGYwNmYxMzNlMGRkMWViMmVjNjg2YjEyNDVkNmQxMzBkNWE1Y2ZjYWEwOWY1MGI1MDQ4MTYxYzIwZWQ4MTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jZgrW9XpC4251gdyx9bRjCEmXIhzzHMDOMBOGoqOTkY)


IF I use one (1) 24 PB key, how many times could it be "cloned" to get 24 PB keys?

To put it another way, 24 PB key would give how many 24 PB keys key out?
