### ISSUE TITLE
We are no longer accepting referral codes. Please continue to sign up with a free account

### ISSUE THREAD

**Issue by Neptune1190** [totoroterror/warp-cloner#38]
keep getting  the output "Failed to register: 400 {"result":null,"success":false,"errors":[{"code":1070,"message":"We are no longer accepting referral codes. Please continue to sign up with a free account."}],"messages":[]}" when trying to clone 2 exabyte keys

**Comment by jogerj** [comment]
> Note: Cloudflare will conclude the referral program for WARP+ on November 1, 2024. At that time, new referral codes will no longer be provided. When your device consumes existing referral allotment you will automatically migrate to the WARP free plan. You will not lose connectivity.
> If you would like to continue using WARP+ beyond that point, you can subscribe by following the upgrade instructions in the app.

https://support.cloudflarewarp.com/hc/en-us/articles/360025588054-How-do-referrals-work

Party's over 😞

**Comment by Jack999** [comment]
but it said " November 1, 2024."
Today is August 21, 2024 stopped?

**Comment by totoroterror** [comment]
> but it said " November 1, 2024." Today is August 21, 2024 stopped?

Yeah, they stopped way earlier than 21 august. You probably still can use "warp boosters" or some other tools like that (until 1st of november), but new keys won't be able to be cloned unless another method found (which is probably never happens).
