### ISSUE TITLE
Failed to add key

### ISSUE THREAD

**Issue by Fortress937** [totoroterror/warp-cloner#9]
I always see this error

![image](https://user-images.githubusercontent.com/119410273/236590223-14fbff86-1b1b-47a9-bb0e-2a40655baee3.png)

will there be a way to fix it?

**Comment by danaenayati** [comment]
I have the same issue.

**Comment by Keeboy99** [comment]
Same here I even put in my own 12pb key and nope

**Comment by Keeboy99** [comment]
I HAVE FIXED THE ISSUE just dm on discord on how to fix it too complicated to say here

Keeboy99#2878

**Comment by totoroterror** [comment]
You need to add your own base_keys and everything will work.

https://github.com/totoroterror/warp-cloner#configuration

**Comment by Fortress937** [comment]
> You need to add your own base_keys and everything will work.
> 
> https://github.com/totoroterror/warp-cloner#configuration

How?
